language: cpp
services:
  - docker
matrix:
  include:
  - os: windows
    env: >-
      HYPERROGUE_USE_GLEW=1
      TRAVIS_OS_NAME=windows
      TRAVIS_BUILD_SYSTEM=Makefile

before_install:
- |-
  # Install msys2 for Windows
  choco uninstall -y mingw
  choco upgrade --no-progress -y msys2
  export msys2='cmd //C RefreshEnv.cmd '
  export msys2+='& set MSYS=winsymlinks:nativestrict '
  export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
  export mingw64="$msys2 -mingw64 -full-path -here -c \$\* --"
  export msys2+=" -msys2 -c \$\* --"
  $msys2 pacman --noconfirm --noprogressbar -Sy mingw-w64-x86_64-gcc
  taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
  export PATH=/C/tools/msys64/mingw64/bin:$PATH
  $msys2 which g++
  $mingw64 which g++
- |-
  # Install SDL
  $msys2 pacman --noconfirm --noprogressbar -Sy mingw-w64-x86_64-SDL mingw-w64-x86_64-SDL_gfx mingw-w64-x86_64-SDL_mixer mingw-w64-x86_64-SDL_ttf
- |-
  # Install GLEW if asked for
  if [[ "$HYPERROGUE_USE_GLEW" == "1" ]]; then
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install -qq libglew-dev
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install glew
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      $msys2 pacman --noconfirm --noprogressbar -Sy mingw-w64-x86_64-glew
    else
      exit 'Unsupported OS'
    fi
  fi
- |-
  # Install libpng if asked for
  if [[ "$HYPERROGUE_USE_PNG" == "1" ]]; then
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      echo 'libpng is installed by default'
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install libpng
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install libpng
    else
      exit 'Unsupported OS'
    fi
  fi
- |-
  # Install autotools if asked for
  $msys2 pacman --noconfirm --noprogressbar -Sy base-devel automake autoconf

script:
- |-
  # Build hyperrogue.
  $mingw64 mingw32-make -f Makefile.simple CXX="${HYPERROGUE_CXX-g++}"
- |-
  # Test hyperrogue.
  ./hyperrogue --help
- |-
  # Test "make dist". ("make distcheck" is expected to fail.)
  if [[ "$TRAVIS_BUILD_SYSTEM" == "autotools" ]]; then make dist; fi
- |-
  # Test "sudo make install".
  if [[ "$TRAVIS_BUILD_SYSTEM" == "autotools" ]]; then sudo make install; fi
